# Generated by Django 2.1.5 on 2019-07-19 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_province', models.CharField(max_length=32, verbose_name='省份')),
                ('address_city', models.CharField(max_length=32, verbose_name='市')),
                ('address_area', models.CharField(max_length=32, null=True, verbose_name='区')),
                ('address_definite', models.CharField(max_length=120, verbose_name='详细地址')),
                ('address_name', models.CharField(max_length=32, verbose_name='收件人')),
                ('address_tel', models.CharField(max_length=11, verbose_name='收件人号码')),
                ('address_default', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_num', models.IntegerField(default=0, null=True, verbose_name='商品数量')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=32, verbose_name='类名')),
                ('category_pid', models.ForeignKey(help_text='父id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='shopapp.Category', verbose_name='关联分类id')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=16, verbose_name='颜色名')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField(verbose_name='评论内容')),
                ('comment_addtime', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('comment_goods_color', models.CharField(max_length=16, null=True, verbose_name='评论的商品颜色')),
                ('comment_goods_size', models.CharField(max_length=16, null=True, verbose_name='评论的商品尺码')),
            ],
        ),
        migrations.CreateModel(
            name='Goods_img',
            fields=[
                ('goods_img_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_img_path', models.CharField(max_length=120, verbose_name='图片路径')),
            ],
        ),
        migrations.CreateModel(
            name='Googs',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('goods_original_price', models.FloatField(null=True, verbose_name='商品原价')),
                ('goods_current_price', models.FloatField(null=True, verbose_name='商品现价')),
                ('goods_month_saled', models.IntegerField(null=True, verbose_name='月销量')),
                ('goods_inventory', models.IntegerField(null=True, verbose_name='现存货')),
                ('goods_addtime', models.DateTimeField(null=True, verbose_name='商品上架时间')),
                ('goods_desc', models.CharField(max_length=255, verbose_name='商品简介')),
                ('goods_content', models.TextField(null=True, verbose_name='商品内容')),
                ('goods_img', models.CharField(max_length=120, null=True, verbose_name='商品图片')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.IntegerField()),
                ('order_pay_way', models.IntegerField()),
                ('order_addtime', models.DateTimeField()),
                ('order_number', models.CharField(max_length=60)),
                ('order_address_province', models.CharField(max_length=32, verbose_name='省份')),
                ('order_address_city', models.CharField(max_length=32, verbose_name='市')),
                ('order_address_area', models.CharField(max_length=32, null=True, verbose_name='区')),
                ('order_address_definite', models.CharField(max_length=120, verbose_name='详细地址')),
                ('order_address_name', models.CharField(max_length=32, verbose_name='收件人')),
                ('order_address_tel', models.CharField(max_length=11, verbose_name='收件人号码')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('order_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_goods_name', models.CharField(max_length=72, verbose_name='订单商品名称')),
                ('order_goods_price', models.FloatField(null=True, verbose_name='订单商品价格')),
                ('order_goods_num', models.IntegerField(default=0, null=True, verbose_name='商品数量')),
                ('order_goods_img', models.CharField(max_length=120, null=True, verbose_name='图片路径')),
                ('order_goods_color', models.CharField(max_length=16, null=True, verbose_name='订单商品颜色')),
                ('order_goods_size', models.CharField(max_length=16, null=True, verbose_name='订单商品尺码')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Googs')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('size_num', models.CharField(max_length=16, verbose_name='尺码大小')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=32)),
                ('user_pwd', models.CharField(max_length=120)),
                ('user_tel', models.CharField(max_length=11, null=True)),
                ('user_extra_money', models.IntegerField(default=0, null=True)),
                ('user_paypwd', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.User'),
        ),
        migrations.AddField(
            model_name='googs',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Size'),
        ),
        migrations.AddField(
            model_name='goods_img',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_goods_img', to='shopapp.Googs'),
        ),
        migrations.AddField(
            model_name='comment',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Googs'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Googs'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.User'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.User'),
        ),
    ]
