# Generated by Django 2.1.5 on 2019-07-20 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Googs',
            new_name='Goods',
        ),
    ]
